### ISSUE TITLE
original_category_group_id - NoneType not allowed

### ISSUE THREAD

**Issue by thewhirlingtwirler** [dmlerner/ynab-api#11]
I am running get_categories() as [documented ](https://github.com/dmlerner/ynab-api/blob/6ad6dc1f8ec1436027bef2a071e411a9f9afab6e/docs/CategoriesApi.md#get_categories) in the first "# example passing only required values which don't have defaults set"
and keep getting an error on 1736 of model_utils.py

ApiValueError: Invalid inputs given to generate an instance of 'CategoryGroupWithCategoriesAllOf'. The input data was invalid for the allOf schema 'CategoryGroupWithCategoriesAllOf' in the composed schema 'CategoryGroupWithCategories'. Error=Invalid type for variable 'original_category_group_id'. Required value type is str and passed type was NoneType at ['received_data']['data']['category_groups'][0]['categories'][0]['original_category_group_id']

Received a similar error with get_transactions(). When providing 'type' param, 'memo' was not allowed as a NoneType, when removing 'type' and only passing budget_id, flag_color was not allowed as a NoneType

Not having any issue with get_accounts() so it's not like my budget ID is wrong or authentication is not working, 
At a loss, it just seems like some optional params are being required, can you help me with what I am missing here?
Apologies if this is a noob question, bit of an amateur myself

**Comment by dmlerner** [comment]
Known issue - see https://github.com/dmlerner/ynab-api/issues/9 and secondarily https://github.com/dmlerner/ynab-api/pull/10

In short, the official swagger spec is broken. The one this repo is built on is hackily hand fixed to be less broken. You could make it even less broken for the specific things in theory (and then regenerate the API).
