### ISSUE TITLE
AttributeError Question

### ISSUE THREAD

**Issue by plasmonresonator** [dmlerner/ynab-api#5]
Hi @dmlerner:
I am pretty inexperienced with github, so please forgive me if raising an issue is not the right way to ask a question, I just couldn't find any other way to reach out.  

I was trying to play with this api, and I can't get past the first example you have.  I am hitting an error when trying to open an instance of the API client and I am getting the error below.  

Any idea why this might be happening?

Thank you!!
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-45-be08a512d40c> in <module>
     14 
     15 # Enter a context with an instance of the API client
---> 16 with ynab_api.ApiClient(configuration) as api_client:
     17     # Create an instance of the API class
     18     api_instance = ynab_api.AccountsApi(api_client)

AttributeError: __enter__

**Comment by dmlerner** [comment]
The API may have been broken at the time. Either way, are you still having the issue? I've just (in theory) fixed it up.

**Comment by dmlerner** [comment]
Closing as inactive

**Comment by ghost** [comment]
Hi @dmlerner , I've realised this is failing as the version published on pypi is still V1: https://pypi.org/project/ynab-api/. Obviously other fixes since then are also missing.
