### ISSUE TITLE
Missing model fields after last regeneration

### ISSUE THREAD

**Issue by Mtbarros** [dmlerner/ynab-api#6]
Hey @dmlerner,

First of all, thanks for the work you've put into this.
I am using your API and I've noticed your last regeneration removed some fields from some models.
I am guessing this wasn't intended?

These are the docs of the ones I've found. All I checked were indeed missing in the models:

docs/BudgetDetail.md
https://github.com/dmlerner/ynab-api/commit/b3cbde56395f694bb7f7cc700bc90b38fd51531b#diff-3319062bcda0b42efafd9120f679d929

docs/CategoryGroupWithCategories.md
https://github.com/dmlerner/ynab-api/commit/b3cbde56395f694bb7f7cc700bc90b38fd51531b#diff-2ec914b83ac1e873109ed4f9c3ca4652

docs/HybridTransaction.md
https://github.com/dmlerner/ynab-api/commit/b3cbde56395f694bb7f7cc700bc90b38fd51531b#diff-14c72b5221c34823dd6f866f06de4093

docs/MonthDetail.md
https://github.com/dmlerner/ynab-api/commit/b3cbde56395f694bb7f7cc700bc90b38fd51531b#diff-9a6cef3909a97afb4c3331bf96d466d9

docs/ScheduledTransactionDetail.md
https://github.com/dmlerner/ynab-api/commit/b3cbde56395f694bb7f7cc700bc90b38fd51531b#diff-673a0f078cd9c631bb78c1dd29babdb8

docs/TransactionDetail.md
https://github.com/dmlerner/ynab-api/commit/b3cbde56395f694bb7f7cc700bc90b38fd51531b#diff-2d211079a91d6df6611dc5d03b1bf5b9

docs/UpdateTransaction.md
https://github.com/dmlerner/ynab-api/commit/b3cbde56395f694bb7f7cc700bc90b38fd51531b#diff-6acada676be02985007bc6fc2f267ce1

Can you confirm this is unintended? Will you be able to regenerate the API?

Cheers!

**Comment by dmlerner** [comment]
I definitely need to regenerate from the swagger spec. It should in principle be easy, but I haven't been able to get the tox test to pass. It looks like it generates many things empty for some reason. I hope to look at this some day, but it's be very reasonable for someone to fork this repo. 

Closing as duplicate of https://github.com/dmlerner/ynab-api/issues/4.
